### ISSUE TITLE
License

### ISSUE THREAD

**Issue by EReeves** [CodeAndWeb/TexturePacker-MonoGameLoader#2]
Could you please add a license? That way I can feel better about using it. :laughing:

**Comment by RandolphBurt** [comment]
Hi @EReeves - As it happens I'm about to transfer this repo across to @CodeAndWeb (The developers of TexturePacker) so they can look after it going forward. As such they are going to add an MIT license 👍

**Comment by CodeAndWeb** [comment]
MIT license added.
